-- Insert property categories
INSERT INTO property_categories(category, subcategory)
    VALUES ('Residential', 'Appartamento'),
('Residential', 'Attico'),
('Residential', 'Mansarda'),
('Residential', 'Terratetto unifamiliare'),
('Residential', 'Terratetto plurifamiliare'),
('Residential', 'Loft'),
('Residential', 'Openspace'),
('Residential', 'Soffitta'),
('Residential', 'Baglio'),
('Residential', 'Baita'),
('Residential', 'Casa colonica'),
('Residential', 'Casale'),
('Residential', 'Chalet'),
('Residential', 'Dammuso'),
('Residential', 'Maso'),
('Residential', 'Masseria'),
('Residential', 'Nuraghe'),
('Residential', 'Rifugio'),
('Residential', 'Rustico'),
('Residential', 'Sasso'),
('Residential', 'Trullo'),
('Residential', 'Villa unifamiliare'),
('Residential', 'Villa bifamiliare'),
('Residential', 'Villa a schiera'),
('Residential', 'Appartamento in villa'),
('Shed', 'Capannone'),
('Shops', 'Locale Commerciale'),
('Shops', 'Laboratorio'),
('Shops', 'Attività Commerciale'),
('Buildings', 'Palazzo/Edificio'),
('Warehouse', 'Magazzino/Deposito'),
('Garage', 'Garage/Box'),
('Garage', 'Posto auto'),
('Office', 'Ufficio/Studio'),
('Land', 'Terreno agricolo'),
('Land', 'Terreno edificabile'),
('Land', 'Terreno non edificabile');

