CREATE TABLE public.properties(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    category text NOT NULL,
    subcategory text NOT NULL,
    street_name text NOT NULL,
    street_number text NOT NULL,
    postal_code text NOT NULL,
    city text NOT NULL,
    state text NULL,
    country text NOT NULL,
    mq smallint NOT NULL,
    floor smallint NULL,
    total_floors smallint NULL,
    rooms smallint NOT NULL,
    kitchens smallint NOT NULL,
    bathrooms smallint NOT NULL,
    heating heating NOT NULL,
    heating_type heating_type NULL,
    heating_fuel heating_fuel NOT NULL,
    air_conditioning air_conditioning NOT NULL,
    energy_class energy_class NOT NULL,
    furnishing furnishing NOT NULL,
    external_fixtures_material external_fixtures_material NOT NULL,
    external_fixtures_glass_type external_fixtures_glass_type NOT NULL,
    condition condition NOT NULL,
    exposure exposure NOT NULL,
    elevator elevator NOT NULL,
    pool boolean NULL,
    construction_year smallint NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL,
    CONSTRAINT properties_pkey PRIMARY KEY (id),
    CONSTRAINT properties_category_fkey FOREIGN KEY (category, subcategory) REFERENCES property_categories(category, subcategory),
    CONSTRAINT properties_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

