CREATE TABLE public.properties(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    category text NOT NULL,
    sub_category text NOT NULL,
    street_name text NOT NULL,
    street_number text NOT NULL,
    postal_code text NOT NULL,
    city text NOT NULL,
    state text NULL,
    country text NOT NULL,
    mq smallint NOT NULL,
    floor smallint NULL,
    total_floors smallint NULL,
    rooms smallint NOT NULL,
    bedrooms smallint NOT NULL,
    kitchens smallint NOT NULL,
    bathrooms smallint NOT NULL,
    heating heating NOT NULL,
    energy_class energy_class NOT NULL,
    furnishing furnishing NOT NULL,
    external_fixtures external_fixtures NOT NULL,
    condition condition NOT NULL,
    exposure exposure NOT NULL,
    elevator boolean NOT NULL,
    pool boolean NULL,
    construction_year smallint NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    user_id uuid NOT NULL,
    CONSTRAINT properties_pkey PRIMARY KEY (id),
    CONSTRAINT properties_category_fkey FOREIGN KEY (category) REFERENCES property_categories(name),
    CONSTRAINT properties_sub_category_fkey FOREIGN KEY (sub_category) REFERENCES property_subcategories(name),
    CONSTRAINT properties_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE
);

