create table properties (
    id uuid not null default gen_random_uuid (),
    category text not null,
    sub_category text not null,
    address text not null,
    mq smallint not null,
    floor smallint null,
    total_floors smallint null,
    rooms smallint not null,
    bedrooms smallint not null,
    kitchens smallint not null,
    bathrooms smallint not null,
    heating heating not null,
    energy_class energy_class not null,
    furnishing furnishing not null,
    external_fixtures external_fixtures not null,
    condition condition not null,
    exposure exposure not null,
    elevator boolean not null,
    pool boolean null,
    construction_year smallint null,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    user_id uuid not null,
    constraint properties_pkey primary key (id),
    constraint properties_category_fkey foreign key (category) references property_categories (name),
    constraint properties_sub_category_fkey foreign key (sub_category) references property_subcategories (name),
    constraint properties_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
);